/**
 * Mock data for Bali Resort properties
 * Used for development and testing
 */

import { Property } from "@/types/property.types";

// Bali resort locations
export const BALI_LOCATIONS = [
  "Seminyak, Bali",
  "Ubud, Bali",
  "Canggu, Bali",
  "Kuta, Bali",
  "Nusa Dua, Bali",
  "Sanur, Bali",
  "Jimbaran, Bali",
  "Uluwatu, Bali",
  "Legian, Bali",
  "Tanah Lot, Bali",
  "Candidasa, Bali",
  "Lovina, Bali",
] as const;

// Location data for search dropdown
export const LOCATION_OPTIONS = [
  {
    id: "seminyak",
    name: "Seminyak",
    region: "Bali Selatan",
    description: "Pantai, Restoran, Nightlife",
    icon: "🏖️",
  },
  {
    id: "ubud",
    name: "Ubud",
    region: "Bali Tengah",
    description: "Sawah, Seni, Budaya",
    icon: "🌾",
  },
  {
    id: "canggu",
    name: "Canggu",
    region: "Bali Selatan",
    description: "Surfing, Cafe, Beach Club",
    icon: "🏄",
  },
  {
    id: "kuta",
    name: "Kuta",
    region: "Bali Selatan",
    description: "Pantai, Shopping, Airport",
    icon: "✈️",
  },
  {
    id: "nusa-dua",
    name: "Nusa Dua",
    region: "Bali Selatan",
    description: "Resort Mewah, Pantai Privat",
    icon: "🌴",
  },
  {
    id: "sanur",
    name: "Sanur",
    region: "Bali Timur",
    description: "Sunrise Beach, Tenang",
    icon: "🌅",
  },
  {
    id: "jimbaran",
    name: "Jimbaran",
    region: "Bali Selatan",
    description: "Seafood, Sunset, Pantai",
    icon: "🦐",
  },
  {
    id: "uluwatu",
    name: "Uluwatu",
    region: "Bali Selatan",
    description: "Cliff, Temple, Surfing",
    icon: "🏛️",
  },
  {
    id: "legian",
    name: "Legian",
    region: "Bali Selatan",
    description: "Pantai, Bar, Entertainment",
    icon: "🎉",
  },
  {
    id: "tanah-lot",
    name: "Tanah Lot",
    region: "Bali Barat",
    description: "Temple, Sunset View",
    icon: "⛩️",
  },
  {
    id: "candidasa",
    name: "Candidasa",
    region: "Bali Timur",
    description: "Snorkeling, Tenang, Alam",
    icon: "🐠",
  },
  {
    id: "lovina",
    name: "Lovina",
    region: "Bali Utara",
    description: "Dolphin, Black Sand Beach",
    icon: "🐬",
  },
];

// Mock Bali resort properties with real coordinates
export const MOCK_BALI_RESORTS: Property[] = [
  {
    id: "1",
    title: "Alila Villas Uluwatu",
    description: "Resort mewah di tebing Uluwatu dengan pemandangan laut yang spektakuler. Setiap villa memiliki kolam renang pribadi dan butler service 24 jam.",
    price_per_night: 3500000,
    location: "Uluwatu, Bali",
    latitude: -8.8291,
    longitude: 115.0849,
    image_urls: [
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&q=80&w=800",
    ],
    amenities: ["Private Pool", "Ocean View", "Butler Service", "Spa", "Restaurant", "WiFi"],
    max_guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    rating: 4.9,
    review_count: 128,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    title: "Four Seasons Resort Ubud",
    description: "Resort eksklusif di tengah hutan hujan Ubud dengan villa-villa yang menghadap lembah sungai Ayung. Pengalaman spa Bali yang autentik.",
    price_per_night: 4200000,
    location: "Ubud, Bali",
    latitude: -8.5069,
    longitude: 115.2624,
    image_urls: [
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&q=80&w=800",
    ],
    amenities: ["Infinity Pool", "Valley View", "Spa", "Yoga", "Restaurant", "WiFi", "Gym"],
    max_guests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 3,
    rating: 4.8,
    review_count: 256,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    title: "W Bali Seminyak",
    description: "Resort modern dan stylish di jantung Seminyak. Akses langsung ke pantai dengan beach club yang iconic dan suasana party yang vibrant.",
    price_per_night: 1850000,
    location: "Seminyak, Bali",
    latitude: -8.6905,
    longitude: 115.1575,
    image_urls: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&q=80&w=800",
    ],
    amenities: ["Beach Access", "Pool", "Beach Club", "Spa", "Restaurant", "Bar", "WiFi"],
    max_guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.7,
    review_count: 312,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    title: "The Mulia Resort Nusa Dua",
    description: "Resort all-suite mewah di Nusa Dua dengan pantai privat sepanjang 300 meter. Kolam renang terbesar di Bali dan 9 restoran pilihan.",
    price_per_night: 2750000,
    location: "Nusa Dua, Bali",
    latitude: -8.8005,
    longitude: 115.2317,
    image_urls: [
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&q=80&w=800",
    ],
    amenities: ["Private Beach", "Multiple Pools", "Spa", "9 Restaurants", "Kids Club", "WiFi"],
    max_guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    rating: 4.9,
    review_count: 445,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    title: "Como Uma Canggu",
    description: "Boutique resort modern di Canggu dengan fokus pada wellness dan surfing. Dekat dengan Echo Beach dan cafe-cafe trendy.",
    price_per_night: 1450000,
    location: "Canggu, Bali",
    latitude: -8.6478,
    longitude: 115.1385,
    image_urls: [
      "https://images.unsplash.com/photo-1615460549969-36fa19521a4f?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1602002418816-5c0aeef426aa?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&q=80&w=800",
    ],
    amenities: ["Pool", "Surf School", "Yoga", "Spa", "Restaurant", "WiFi", "Bike Rental"],
    max_guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.6,
    review_count: 189,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    title: "Ayana Resort Jimbaran",
    description: "Resort terintegrasi terbesar di Bali dengan Rock Bar yang legendaris. Pemandangan sunset Jimbaran yang tak terlupakan.",
    price_per_night: 2200000,
    location: "Jimbaran, Bali",
    latitude: -8.7892,
    longitude: 115.1556,
    image_urls: [
      "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&q=80&w=800",
    ],
    amenities: ["Rock Bar", "12 Pools", "Private Beach", "Spa", "Golf", "WiFi", "Shuttle"],
    max_guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    rating: 4.8,
    review_count: 567,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "7",
    title: "Padma Resort Legian",
    description: "Resort keluarga di tepi pantai Legian dengan taman tropis yang luas. Sunset lounge dan infinity pool menghadap laut.",
    price_per_night: 1150000,
    location: "Legian, Bali",
    latitude: -8.7056,
    longitude: 115.1686,
    image_urls: [
      "https://images.unsplash.com/photo-1584132915807-fd1f5fbc078f?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=800",
    ],
    amenities: ["Beachfront", "Infinity Pool", "Kids Club", "Spa", "Restaurant", "WiFi"],
    max_guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    rating: 4.5,
    review_count: 423,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "8",
    title: "Tanah Gajah Ubud",
    description: "Resort heritage di tengah sawah Ubud dengan suasana pedesaan Bali yang autentik. Pengalaman budaya dan kuliner lokal.",
    price_per_night: 2850000,
    location: "Ubud, Bali",
    latitude: -8.4892,
    longitude: 115.2789,
    image_urls: [
      "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&q=80&w=800",
    ],
    amenities: ["Rice Field View", "Pool", "Cooking Class", "Spa", "Restaurant", "WiFi"],
    max_guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.7,
    review_count: 156,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "9",
    title: "Puri Santrian Sanur",
    description: "Resort tradisional Bali di pantai Sanur dengan arsitektur klasik dan taman yang indah. Suasana tenang untuk relaksasi.",
    price_per_night: 750000,
    location: "Sanur, Bali",
    latitude: -8.6783,
    longitude: 115.2631,
    image_urls: [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&q=80&w=800",
    ],
    amenities: ["Beach Access", "Pool", "Spa", "Restaurant", "WiFi", "Garden"],
    max_guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.4,
    review_count: 234,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "10",
    title: "Six Senses Uluwatu",
    description: "Resort wellness premium di tebing Uluwatu dengan fokus pada sustainability dan pengalaman holistik. Pemandangan 360 derajat.",
    price_per_night: 4800000,
    location: "Uluwatu, Bali",
    latitude: -8.8356,
    longitude: 115.0912,
    image_urls: [
      "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&q=80&w=800",
    ],
    amenities: ["Cliff View", "Private Pool", "Wellness Center", "Organic Restaurant", "Yoga", "WiFi"],
    max_guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    rating: 4.9,
    review_count: 89,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "11",
    title: "Potato Head Suites",
    description: "Boutique hotel artsy di Seminyak dengan desain unik dan beach club yang iconic. Pengalaman lifestyle modern Bali.",
    price_per_night: 1650000,
    location: "Seminyak, Bali",
    latitude: -8.6823,
    longitude: 115.1534,
    image_urls: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&q=80&w=800",
    ],
    amenities: ["Beach Club", "Pool", "Art Gallery", "Restaurant", "Bar", "WiFi"],
    max_guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.6,
    review_count: 278,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "12",
    title: "The Legian Seminyak",
    description: "Resort butik mewah di tepi pantai Seminyak dengan suite-suite yang elegan dan layanan personal yang luar biasa.",
    price_per_night: 2100000,
    location: "Seminyak, Bali",
    latitude: -8.6867,
    longitude: 115.1545,
    image_urls: [
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&q=80&w=800",
    ],
    amenities: ["Beachfront", "Pool", "Spa", "Fine Dining", "Butler", "WiFi"],
    max_guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    rating: 4.8,
    review_count: 167,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

// Helper function to format Indonesian Rupiah
export function formatRupiah(amount: number): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

// Helper function to get random properties
export function getRandomProperties(count: number = 6): Property[] {
  const shuffled = [...MOCK_BALI_RESORTS].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}


// Mock bookings for development
export const MOCK_BOOKINGS = [
  {
    id: "booking-1",
    property_id: "1",
    user_id: "user-1",
    start_date: "2026-02-15",
    end_date: "2026-02-20",
    total_price: 17500000, // 5 malam x Rp 3.500.000
    status: "confirmed" as const,
    guests: 2,
    created_at: new Date().toISOString(),
    property: MOCK_BALI_RESORTS[0],
  },
  {
    id: "booking-2",
    property_id: "3",
    user_id: "user-1",
    start_date: "2026-03-10",
    end_date: "2026-03-15",
    total_price: 9250000, // 5 malam x Rp 1.850.000
    status: "pending" as const,
    guests: 2,
    created_at: new Date().toISOString(),
    property: MOCK_BALI_RESORTS[2],
  },
];
